server:
  port: 8222
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9098/auth/realms/microservices
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-server
          uri: lb:http://CUSTOMER-SERVER
          predicates:
            - Path=/api/v1/customers/**
        - id: product-server
          uri: lb:http://PRODUCT-SERVER
          predicates:
            - Path=/api/v1/products/**
        - id: order-server
          uri: lb:http://ORDER-SERVER
          predicates:
            - Path=/api/v1/orders/**
        - id: order-line-server
          uri: lb:http://ORDER-SERVER
          predicates:
            - Path=/api/v1/order-lines/**
        - id: payment-server
          uri: lb:http://PAYMENT-SERVER
          predicates:
            - Path=/api/v1/payments/**